[project]
name = "vietnam-travel-magazine"

[services.frontend]
path = "apps/frontend-next"
start = "npm run build && npm run start"

[services.cms]
path = "apps/strapi-cms"
start = "npm run build && npm run develop"

[variables]
  CMS_URL = { value = "http://localhost:1337" }
  PUBLISH_TIME = { value = "09:30" }
